server:
  port: 8888

mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: boot.spring.po

spring:
  datasource:
    url: jdbc:mysql://localhost:3305/activiti
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 1234
  activiti:
    database-schema-update: true
    check-process-definitions: true
    process-definition-location-prefix: classpath:/process/
    history-level: full

logging:
  config: classpath:log4j2.xml

#spring.main.allow-bean-definition-overriding: true
